### ISSUE TITLE
Implement Cloudflare D1 driver

### ISSUE THREAD

**Issue by invisal** [invisal/libsql-studio#39]

**Comment by Chinoman10** [comment]
If it helps, there's this other REPO that serves as a "D1 browser" of sorts:
https://github.com/JacobLinCool/d1-manager

I very much prefer this (libsql) interface however. Would love to also open and edit local .sqlite files so I don't have to use https://sqliteviewer.app/ (which actually doesn't allow editing), but I see there's an issue for that too I think (#70 ).

**Comment by invisal** [comment]
> If it helps, there's this other REPO that serves as a "D1 browser" of sorts: https://github.com/JacobLinCool/d1-manager
> 
> I very much prefer this (libsql) interface however. Would love to also open and edit local .sqlite files so I don't have to use https://sqliteviewer.app/ (which actually doesn't allow editing), but I see there's an issue for that too I think ( #70 ).

LibSQL Studio can also ope .sqlite file. We have SQLite playground
https://libsqlstudio.com/playground/client

You can click open or drag file in.

For Cloudflare D1, it shouldn't be difficult to implement, just we are not sure if there is high demand for this Cloudflare D1. The only challenge is CORS. But we can bypass it by proxy the request via our server.

**Comment by Chinoman10** [comment]
I just tested it out!

Few things:
- Drag & drop didn't work; it would always open a new tab instead 🤷 
- Once I picked the .sqlite file from the filesystem, it opened without a hitch 👍 
- I was expecting it to make a `select * from <insert-table-name> limit 50` when I (single) clicked a table's name on the left, but when it didn't do anything other than select it, I simply double-clicked and it "opened" as expected.
- Making changes and committing them makes sense in a DB environment, however I was expecting the commit to change the DB on my FS that I had opened (_so, actually "opening" the file, rather than "uploading" it_). I had to realize that to use the changes I made, I had to download the DB and replace the original file with the "dump" (which is the DB itself, not an actual dump file (_which AFAIK are usually sets of instructions to achieve the same DB state_)).

Despite those nuances, this was good enough that I'll start using it instead of sqliteviewer moving forward :) and obviously recommend it to other folks too.

As far as D1 goes, it would make my day good sir <3 I hope one day I am able to pay it back ^^ I love FOSS and I'd love to reach a position where I can support these projects :)

**Comment by invisal** [comment]
@Chinoman10 

> Drag & drop didn't work; it would always open a new tab instead 🤷
What are you trying to drag that open new tab?

> however I was expecting the commit to change the DB on my FS that I had opened
This is limitation of the browser (for security reason). The only way to workaround is to make it as browser extension which allows to save back to opened file.

> As far as D1 goes, it would make my day good sir
Let me try to finish the D1 this weekend. It shouldn't be hard to implement

**Comment by Chinoman10** [comment]
> @Chinoman10
> 
> > Drag & drop didn't work; it would always open a new tab instead 🤷
> 
> What are you trying to drag that open new tab?

A .sqlite file (a local SQLite DB).

> > however I was expecting the commit to change the DB on my FS that I had opened
> 
> This is limitation of the browser (for security reason). The only way to workaround is to make it as browser extension which allows to save back to opened file.

Makes sense I think, thanks for explaining 🙏  I think the 'extension workaround' is what Google did so people could work on their G. Docs, etc. offline.

> > As far as D1 goes, it would make my day good sir
> 
> Let me try to finish the D1 this weekend. It shouldn't be hard to implement

There's no rush to it, but I'd be super happy about it for sure ^^
I'm wondering how you'll get the access going though, there's multiple ways to get it done.
- Cloudflare API Keys with access to the D1s of the account;
- Through native Cloudflare DB bindings (that's how "D1 Manager" does it) through the dashboard (_or the `wrangler.toml` file_)...

Other than that I'm not sure if there are other ways that don't involve a wrapper (_that would need a native way to connect anyway, so would be pointless_).

**Comment by invisal** [comment]
We will use API Key which is how TablePlus and Dataflare are using.

**Comment by invisal** [comment]
For save directly to file when open local SQLite file. I saw this https://developer.chrome.com/docs/capabilities/web-apis/file-system-access maybe it is possible

**Comment by invisal** [comment]
@Chinoman10 Cloudflare driver is done. It will be available in the next release which will be on Monday 22th this month.

**Comment by Chinoman10** [comment]
> @Chinoman10 Cloudflare driver is done. It will be available in the next release which will be on Monday 22th this month.

Just wanted to say that I tried it out today with a few D1 DBs and so far the experience has been great, thank you so much for building this out!
Right now I'm just using it locally on my browser (_tho I did create a new account because I like the project_!), but I might try self-hosting it one day.

Feel free to let me know how I can further support this project beyond giving a star on this repo and spreading the word :)

**Comment by invisal** [comment]
@Chinoman10 Brave for some reason does not support https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle I think I need to do fallback for browser that does not support this one. Safari, Chrome and Firefox support this already. I will investigate which other browser that does not support.

**Comment by invisal** [comment]
Brave does support it but you need to enable the flag

https://github.com/brave/brave-browser/issues/18979

**Comment by Chinoman10** [comment]
> Brave does support it but you need to enable the flag
> [brave/brave-browser#18979](https://github.com/brave/brave-browser/issues/18979)

Perfect! <insert chef's kiss meme>
Thank you 🙏 

( _I have one last question (off-topic for this issue tho): will you consider adding Postgres as well someday? We're currently using Adminer and it feels like I'm using a decades old product... and I think it's done in PHP too_ 🤮 )

**Comment by invisal** [comment]
Eventually, we will support MySQL and PostgreSQL (it is where big audience). But I am not sure what will be the timeline. 

LibSQL Studio is very new. (6~7 months old). So we need to catch up with other GUI in term of feature first before we expand to more drivers.

The good thing is that I used to write PostgreSQL/MySQL GUI (https://github.com/querymx/querym) before as well, so when I want to implement those driver, I will have some existing code before. ^^

**Comment by Chinoman10** [comment]
That's pretty dope! I might download that one and give it a shot when I feel frustrated about Adminer again 😅
Looking forward to your next releases of LibSQL, I'll try and follow closely ^^ (_and help spread the word_)
